kind: pipeline
name: default

steps:
  - name: lint
    image: node:12-alpine
    environment:
      NODE_ENV: development
    commands:
      - npm ci
      - npm run lint
      - npm run prettier
  - name: test
    image: node:12-alpine
    environment:
      NODE_ENV: development
    commands:
      - npm test
  - name: upload coverage
    image: md5lukas/drone-coveralls
    settings:
      token:
        from_secret: coveralls_token
      files:
        - ./coverage/lcov.info
  - name: publish
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: md5lukas/drone-mvn-settings
      auto_tag: true
    when:
      event:
        - tag

trigger:
  branch:
    exclude:
      - dependabot/**
