name: Test

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12
      id: cache
    - uses: actions/cache@v1
      with:
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
    - run: npm ci
      if: steps.cache.outputs.cache-hit != 'true'
      env:
        NODE_ENV: development
    - name: Prettier
      run: npm run prettier
    - name: ESLint
      run: npm run lint
    - name: Test
      run: npm test
      env:
        CI: true
        NODE_ENV: development
    - name: Coveralls
      uses: coverallsapp/github-action@v1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
